server:
  port: 9100

fhir:
  server:
    url: http://localhost:9504/hapi-fhir-jpaserver/fhir/
#
#security:
#  oauth2:
#    client:
#      client-id: first-client
#      client-secret: noonewilleverguess