server:
  port: 9410


logging:
  level:
    org.springframework.security: DEBUG

spring:
  main:
    allow-bean-definition-overriding=true:

fhircast:
  fhirserver:
    url: http://hapi.fhir.org/baseR4
    memory: false
  includeEntity: false
  alive:
    active: true
    period: 10000

