server:
  port: 9601

proxy:
  base: fhir
  fhirserver:
    url: http://localhost:9504/hapi-fhir-jpaserver/fhir/

  authorization-endpoint: http://localhost:8080/oauth/authorize
  token-endpoint: http://localhost:8080/oauth/token

logging:
  level:
    org.springframework.security: DEBUG

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8080/oauth/introspect
